name: Schedule Clicker
on:
  workflow_dispatch:
  #schedule:
    #- cron: "*/5 0-23 * * *"
permissions:
  contents: read
  pull-requests: write
  actions: read
  checks: write
  issues: read
  deployments: write
env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev python3-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Python 버전 선택
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_clicker.txt
      - name: Run Scraper
        run: python -m src.clicker # 크롤링을 실행하는 스크립트 파일의 이름
